[build]
  base = "ExpenseTrackerWebsite/client/expense-tracker"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://expensetracker-api.up.railway.app/api"
